# LAB - DATA CLEANING

Import Pandas Library

In [1]:
import pandas as pd

Read CSV file from directory

In [2]:
data = pd.read_csv('C:/Users/leandro/desktop/ironhack/module-1/Data-Cleaning/data/datacopy.csv')

Check data using head function

In [3]:
data.head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.c,2016.09.18.c,5993,NaN,NaN
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.b,2016.09.18.b,5992,NaN,NaN
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,...,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.18.a,2016.09.18.a,5991,NaN,NaN
3,2016.09.17,17-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Thirteenth Beach,Surfing,Rory Angiolella,M,...,NaN,"The Age, 9/18/2016",2016.09.17-Angiolella.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.17,2016.09.17,5990,NaN,NaN
4,2016.09.15,16-Sep-16,2016,Unprovoked,AUSTRALIA,Victoria,Bells Beach,Surfing,male,M,...,2 m shark,"The Age, 9/16/2016",2016.09.16-BellsBeach.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016.09.16,2016.09.15,5989,NaN,NaN

In [50]:
#Values counts in Year column
data['Year'].value_counts()

2015    139
2011    128
2014    125
0       124
2013    122
       ...
1742      1
1758      1
1818      1
1822      1
1595      1
Name: Year, Length: 232, dtype: int64

In [51]:
# Display all columns by given year==2011
pd.set_option('display.max_columns', None)
data[(data['Year']==2011)].head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
606,2011.12.31,31-Dec-11,2011,Unprovoked,USA,Florida,"Jupiter, Palm Beach County",NaN,male,M,NaN,Hand injured,N,18h00,NaN,"Palm Beach Post, 12/31/2011",2011.12.31-Jupiter.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.12.31,2011.12.31,5387,NaN,NaN
607,2011.12.26.R,Reported 26-Dec-2011,2011,Invalid,ANTIGUA,St John's,Fort James Beach,Swimming,"Veron Edwards, Sr.",M,NaN,Bitten on right hand & wrist,N,Early morning,Shark involvement not confirmed,"D. Francis, Caribarena, 12/26/2011",2011.12.26.R-Edwards.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.12.26.R,2011.12.26.R,5386,NaN,NaN
608,2011.12.25,25-Dec-11,2011,Unprovoked,ECUADOR,Santa Elena,BarandË™a Beach,Surfing,FÃˆlix JË™nior Lainez Trejos,M,23,Lacerations to left thigh and calf,N,18h00,NaN,"A. Brenneka, SharkAttackSurvivors.com",2011.12.25-Trejos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.12.25,2011.12.25,5385,NaN,NaN
609,2011.12.23,23-Dec-11,2011,Unprovoked,USA,Florida,New Smyrna Beach,Surfing,Will Futato,M,27,Laceration to ankle,N,12h30,NaN,"Daytona Beach News-Journal, 12/24/2011",2011.12.23-Futato.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.12.23,2011.12.23,5384,NaN,NaN
610,2011.12.21.b,21-Dec-11,2011,Provoked,USA,Hawaii,"Makahuena Point, Kauai",Canoeing,Keone Miyake,M,NaN,"No injury, after kayak collided with the shark...",N,NaN,7' to 8' shark,"A. Brenneka, SharkAttackSurvivors.com",2011.12.21.b-Miyake.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2011.12.21.b,2011.12.21.b,5383,NaN,NaN

Perfom dataframe analysis
Statistics - Shape - Size - data type

In [19]:
# Dataframe Statistics
data.describe()

              Year  original order
count  5992.000000     5992.000000
mean   1925.204606     2997.548899
std     286.473712     1729.860210
min       0.000000        2.000000
25%    1942.000000     1499.750000
50%    1975.000000     2997.500000
75%    2003.000000     4495.250000
max    2016.000000     5993.000000

In [26]:
# Dataframe composition
d_shape=data.shape
print('Rows:',d_shape[0] , 'Columns:',d_shape[1])

Rows: 5992 Columns: 24

In [36]:
#Data type value counts
data.dtypes.value_counts()

object    22
int64      2
dtype: int64

In [27]:
# Data Size(Rows x Columns)
data.size

143808

In [30]:
#data type 
data.dtypes

Case Number               object
Date                      object
Year                       int64
Type                      object
Country                   object
Area                      object
Location                  object
Activity                  object
Name                      object
Sex                       object
Age                       object
Injury                    object
Fatal (Y/N)               object
Time                      object
Species                   object
Investigator or Source    object
pdf                       object
href formula              object
href                      object
Case Number.1             object
Case Number.2             object
original order             int64
Unnamed: 22               object
Unnamed: 23               object
dtype: object

In [32]:
#data type Index 
data.dtypes.index

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23'],
      dtype='object')

In [33]:
# Column names
for col in data.columns:
    print(col)

Case Number
Date
Year
Type
Country
Area
Location
Activity
Name
Sex
Age
Injury
Fatal (Y/N)
Time
Species
Investigator or Source
pdf
href formula
href
Case Number.1
Case Number.2
original order
Unnamed: 22
Unnamed: 23

In [58]:
x = data.isnull().sum()
type(x)

pandas.core.series.Series

In [61]:
null_cols = data.isnull().sum()
# print(null_cols)
null_cols[null_cols > 0]

Country                     43
Area                       402
Location                   496
Activity                   527
Name                       200
Sex                        567
Age                       2681
Injury                      27
Fatal (Y/N)                 19
Time                      3213
Species                   2934
Investigator or Source      15
href formula                 1
href                         3
Unnamed: 22               5991
Unnamed: 23               5990
dtype: int64

In [59]:
#Null values
data.isnull().head()

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True
3,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,False,False,False,False,False,False,False,True,True
4,False,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,False,False,False,False,True,True

In [60]:
null_displ = data[(data['Year'].isnull()==True)]
null_displ.head(5)

Empty DataFrame
Columns: [Case Number, Date, Year, Type, Country, Area, Location, Activity, Name, Sex , Age, Injury, Fatal (Y/N), Time, Species , Investigator or Source, pdf, href formula, href, Case Number.1, Case Number.2, original order, Unnamed: 22, Unnamed: 23]
Index: []

In [65]:
stats = data.describe().transpose()
stats.head()

,count,mean,std,min,25%,50%,75%,max
Year,5992.0,1925.204606,286.473712,0.0,1942.00,1975.0,2003.00,2016.0
original order,5992.0,2997.548899,1729.860210,2.0,1499.75,2997.5,4495.25,5993.0

In [70]:
stats['IQR'] = stats['75%'] - stats['25%']
stats.head()

,count,mean,std,min,25%,50%,75%,max,IQR
Year,5992.0,1925.204606,286.473712,0.0,1942.00,1975.0,2003.00,2016.0,61.0
original order,5992.0,2997.548899,1729.860210,2.0,1499.75,2997.5,4495.25,5993.0,2995.5

In [68]:
import numpy as np
low_variance = []

for col in data._get_numeric_data(): 
    minimum = min(data[col])
    ninety_perc = np.percentile(data[col], 50)
    if ninety_perc == minimum:
        low_variance.append(col)

print(low_variance)
print(minimum)

[]
2

In [69]:
data.iloc[0][0]

'2016.09.18.c'

In [71]:
data['Country']

0                      USA
1                      USA
2                      USA
3                AUSTRALIA
4                AUSTRALIA
               ...
5987             AUSTRALIA
5988             AUSTRALIA
5989                   USA
5990                PANAMA
5991    CEYLON (SRI LANKA)
Name: Country, Length: 5992, dtype: object

In [72]:
print(set(data['Country']))

{nan, 'CHILE', 'BRITISH NEW GUINEA', 'PACIFIC OCEAN ', 'KENYA', 'CAYMAN ISLANDS', 'CRETE', 'NEW GUINEA', 'THAILAND', 'SOUTH CHINA SEA', 'MALDIVE ISLANDS', 'NICARAGUA ', 'NEVIS', 'GUYANA', 'ITALY', 'CHINA', 'SLOVENIA', 'ARGENTINA', 'BARBADOS', 'FEDERATED STATES OF MICRONESIA', 'PALAU', 'SYRIA', 'CURACAO', 'SIERRA LEONE', 'NIGERIA', 'KIRIBATI', 'EQUATORIAL GUINEA / CAMEROON', 'SINGAPORE', 'SEYCHELLES', 'ANGOLA', 'GABON', 'IRAQ', 'MEDITERRANEAN SEA?', 'HONG KONG', 'SOUTH PACIFIC OCEAN', 'LEBANON', 'PARAGUAY', 'CENTRAL PACIFIC', 'NORTHERN MARIANA ISLANDS', 'PANAMA', 'NETHERLANDS ANTILLES', 'VIETNAM', 'MALTA', 'Coast of AFRICA', 'TUVALU', 'INDIA', 'ISRAEL', 'INDONESIA', 'BRAZIL', 'BRITISH VIRGIN ISLANDS', 'URUGUAY', 'BERMUDA', 'NORTH PACIFIC OCEAN', 'NORTHERN ARABIAN SEA', 'SOUTH AFRICA', 'JAMAICA', 'PORTUGAL', 'Between PORTUGAL & INDIA', 'JAPAN', 'NORTH ATLANTIC OCEAN', 'GUATEMALA', 'PALESTINIAN TERRITORIES', 'RED SEA', 'GHANA', 'FIJI', 'SWEDEN', 'UNITED ARAB EMIRATES (UAE)', 'EGYPT / ISRAEL', 'ALGERIA', 'SOUTH ATLANTIC OCEAN', 'HAITI', 'BRITISH ISLES', 'TRINIDAD & TOBAGO', 'INDIAN OCEAN?', 'CARIBBEAN SEA', 'JAVA', 'St Helena', 'GRENADA', 'TASMAN SEA', 'KOREA', 'NAMIBIA', 'RUSSIA', 'MEXICO ', 'ARUBA', 'BELIZE', 'SPAIN', 'NEW ZEALAND', 'COOK ISLANDS', 'GULF OF ADEN', 'ICELAND', 'GREECE', ' TONGA', 'GUINEA', 'LIBERIA', 'TURKEY', 'AZORES', 'MEXICO', ' PHILIPPINES', 'TONGA', 'SCOTLAND', 'OKINAWA', 'BANGLADESH', 'TUNISIA', 'GUAM', 'DIEGO GARCIA', 'SAUDI ARABIA', 'MALAYSIA', 'Sierra Leone', 'RED SEA?', 'MARSHALL ISLANDS', 'ST. MARTIN', 'NICARAGUA', 'UNITED ARAB EMIRATES', 'SOUTH KOREA', 'MARTINIQUE', 'ANDAMAN / NICOBAR ISLANDAS', 'BRITISH WEST INDIES', 'ECUADOR', 'EGYPT ', 'EL SALVADOR', 'RED SEA / INDIAN OCEAN', 'CYPRUS', 'ST. MAARTIN', 'BAY OF BENGAL', 'BAHREIN', 'NORWAY', 'MAURITIUS', 'CROATIA', 'LIBYA', 'SOLOMON ISLANDS / VANUATU', 'SAMOA', 'OCEAN', 'GRAND CAYMAN', 'INDIAN OCEAN', 'TANZANIA', 'MID ATLANTIC OCEAN', 'Seychelles', 'CAPE VERDE', 'ENGLAND', 'THE BALKANS', 'IRAN / IRAQ', 'MICRONESIA', 'YEMEN ', 'SAN DOMINGO', 'FRENCH POLYNESIA', 'PERSIAN GULF', 'ATLANTIC OCEAN', 'JOHNSTON ISLAND', 'SOLOMON ISLANDS', 'CUBA', 'PHILIPPINES', 'PACIFIC OCEAN', 'CEYLON (SRI LANKA)', 'IRAN', 'MOZAMBIQUE', 'NEW BRITAIN', 'MONTENEGRO', 'ANTIGUA', 'GEORGIA', 'SOMALIA', 'UNITED KINGDOM', 'IRELAND', 'COSTA RICA', 'NORTH SEA', 'DOMINICAN REPUBLIC', 'FALKLAND ISLANDS', 'Fiji', 'ITALY / CROATIA', 'GREENLAND', 'PUERTO RICO', 'NEW CALEDONIA', 'BAHAMAS', 'PAPUA NEW GUINEA', 'AMERICAN SAMOA', 'REUNION', 'TURKS & CAICOS', 'AUSTRALIA', 'VENEZUELA', 'SUDAN', 'MAYOTTE', 'SRI LANKA', 'USA', 'TAIWAN', 'VANUATU', 'MONACO', 'BURMA', 'MID-PACIFC OCEAN', 'ASIA?', 'WESTERN SAMOA', 'HONDURAS', 'FRANCE', 'COLUMBIA', 'KUWAIT', 'MADAGASCAR', 'SUDAN?', 'SOUTHWEST PACIFIC OCEAN', 'ADMIRALTY ISLANDS', 'DJIBOUTI', 'SENEGAL', 'CANADA', 'MEDITERRANEAN SEA', 'NORTH ATLANTIC OCEAN ', 'EGYPT', 'YEMEN'}

In [75]:
data['Case Number.1'] = data['Case Number.1'].str.replace('.', '/')
print(set(data['Case Number.1']))

{'2007/05/07/b', '1960/08/10', '2009/02/18', '2012/03/01', '1832/01/23/R', '2013/08/11', '1963/12/26/a', '1969/09/06', '2008/08/30/c', '2015/09/06', '2006/08/15', '1963/10/15', '1999/03/18/b', '1975/11/19/b', '1912/02/19', '1907/10/16/R', '1956/02/10/R', '1960/01/13', '2000/07/15/a', '1989/09/09/a', '1958/01/19', '1989/06/03', '1958/06/02/R', '1897/10/15', '1931/08/18', '1916/07/13/b', '1959/08/15/a', '1938/01/21', 'ND/0086', '1985/00/00/a', '1972/08/08', '2005/11/12', '1895/06/13/R', '1830/07/02/R', '2010/12/05', '1981/06/12', '1940/01/23', '1964/02/10', '2007/12/14', '1945/00/00/c', '1966/08/13', '2011/06/06/R', '1969/07/22', '1964/01/21', '1995/00/00/c', '1958/11/23', '1931/03/22', '2007/08/19/c', '1926/07/23', '2007/07/21', '1975/07/26/b', '1965/05/29', '1959/08/11', '1957/12/23', '1878/00/00', '1847/11/30', '2006/09/03/b', '1999/10/01', '1988/07/04/a', '1951/03/26', '1837/01/17', '1986/09/00/b', '1928/01/00', '2010/09/13', '1993/06/30', '2014/11/17', '2009/01/24/c', '1554/00/00', '1984/09/11', '1917/09/21', '1871/05/22/R', '1967/11/00', '1947/08/04', '1959/05/07', '1997/02/21', '1944/00/00/c', '1847/03/11', '1947/10/28', '1981/07/20', '2016/09/01', '1959/07/23/b', '1992/07/08/a', '1951/01/03', 'ND/0091', '2015/07/08', '2013/09/29/a', '1994/01/31/b', '1955/08/26', '1944/03/26/a', '2006/05/10', '1950/01/16', '1917/07/15', '2000/06/19', '1982/06/26/b', '2013/07/17/R', '1894/07/15/R', '1956/03/25', '1877/04/07', '1877/12/12', '1852/08/07', '1989/06/06', '1991/08/30', '1889/11/29/R', '2004/12/16', '1855/00/00', '1962/01/21', '1997/07/17', '2014/02/08', '1886/05/06', '1954/10/02/a', 'ND/0018', '2005/03/05', '1963/06/01/a', '2010/07/02/a', '1968/12/26', '2003/09/14/c', '2006/01/11', '1868/00/00/a', '1983/12/07', '1912/01/01', 'ND/0030', '2007/08/19/b', '2013/01/21/R', '1925/08/02', '1966/02/27', '1962/08/31/R', '1943/05/17/b', '1996/10/00', '1988/10/23', '1991/03/03', '1936/03/22', '1930/12/13', '1905/05/22', '1901/00/00', '1858/08/29', '1990/00/00', '1949/00/00/a', '1700/00/00/a', '1985/01/16', '2003/10/31/c', '2015/01/16', '1947/11/14/b', '1930/12/02', '1888/07/04', '1928/01/21/a', '1957/05/00', '1947/07/15', '1926/00/00/c', '2016/04/22', '1995/11/17', '1955/12/11', '1902/07/06', '2009/07/24/b', '2010/10/02/b', '1913/08/26/R', '1978/12/29', '1979/12/01', '1998/07/06/b', '1933/02/12', '1990/12/26', '1990/05/13', '1974/07/20', 'ND/0085', '1899/00/00/c', '1994/12/09/a', '1957/04/22', '1952/10/12', '2009/10/09', '1983/05/24', '1996/10/09', '1998/04/26', '1938/06/17', '2015/07/23/b', '2005/09/22', '1983/07/12/a', '1987/10/11', 'ND/0003', '1994/09/11/R', '2012/08/26', '1996/10/03/a', '1959/07/03/a & b', '1923/06/16', '1929/04/26/R', '1949/01/14', '2015/05/29/a', '1868/01/04/R', '2002/01/30/a', '1984/12/03', '1937/07/16/R', '1974/04/25/R', '1883/00/00/a', '1927/01/03', '1956/08/20', '1812/07/00', '1996/02/05', '1924/07/14', '1950/12/16', 'ND-0107', '2010/08/07/b', '2011/09/17', '1962/07/20', '1992/11/05/b', '1996/07/23/a', '1959/00/00/f', '2013/12/13', '1957/00/00/h', '2012/11/19', '2004/05/22/b', '1925/03/10', '1942/06/00', '1938/05/26', '1999/01/03/R', '2001/08/31', '1911/09/17', '2008/12/27/a', '1840/00/00/a', '1947/01/05', '1926/10/23/a', '1877/01/28', '1902/04/00', '1886/03/06/R', '2008/04/26/b', '1871/08/29/R', '2011/10/20', '2009/01/23', '1974/02/00/b', '1999/09/29', '1924/02/08', '1962/01/26', 'ND/0104', '2005/11/02/b', '2004/11/15', '2008/07/25/b', '2005/04/16/a', '2013/02/27', '1906/04/14', '1956/09/13', '2004/10/06', '1989/08/29', '1907/12/21', '1896/00/00/b', '1991/02/24', '1968/04/11/R', '1992/09/00', '2011/03/29/R', '1994/12/11', '1877/02/17/R', '1888/10/23/R', '2016/05/03', '1936/02/20//R', '2005/01/19', '1894/06/15/a/R', '1936/04/22', '1839/04/14', '2008/00/00/a', '1976/03/02', '2004/04/07', '1974/09/00', '1880/11/25', '1965/12/19', '1959/01/02', '2008/06/21', '1999/08/26', '1932/00/00', '2003/04/15', '2002/05/07', '2002/07/09/b', '2013/06/27', '1927/00/00/b', '1968/12/02', '1909/08/13', '1985/05/26', '2004/03/22', '1943/05/17/a', '1899/07/08/R', '1890/05/14', '1961/06/06/R', '1964/05/30', '1992/12/23', '2009/12/20/a', '2002/04/21', '1904/00/00/c', '2005/10/22', '1883/12/19', '1959/01/17/a', '2008/02/07', '2012/09/24', '2010/07/23', '1878/10/24/R', '2006/04/09/b', '2002/12/21', '1972/01/01/a', '1945/08/19', '1959/06/14/b', '1955/08/04/R', '1961/01/01', '1963/12/26/b', '1638/00/00/R', '1985/07/19', '2002/10/30', '1966/00/00', '1924/01/29', '2002/09/16/a', '1899/09/11/R', '1953/07/00', '1929/01/12', '2008/03/28/b', '1931/00/00/b', '1988/07/23', '1987/05/25', '1929/02/08', '1993/03/27', '1935/03/20', '1984/01/05', '1961/00/00/e', '1949/05/13', '1852/00/00', '2015/04/24/c', '2002/09/29', '1993/09/09', '1938/10/05', '1973/11/25', '1959/07/25/a', '2015/06/01', '2012/09/10', '2005/04/17/R', '1950/07/21', '2001/04/12/d', '1987/04/01', '1933/05/23', '1980/04/00', '2003/06/24/c', '1931/08/25', '1955/04/00', '1971/04/16R', '2013/08/26', '2009/04/06/a', '1894/11/28', '1986/11/30', '1966/01/15', '1999/08/24', '1995/00/00/b', '1997/04/20', '1982/02/14/a', '2011/05/29', '1989/02/15', '1906/04/27/R', '2016/07/15', '2014/10/02/b', '1954/06/27', '1912/05/04', '1963/04/12', '1906/01/28', '1904/02/07', '1839/11/17', '1964/02/08', '1967/08/25', '2013/04/24', '2015/08/20', '2010/06/27', '1921/09/00', '1998/04/17', '1963/12/04/R', '2012/05/20', '1970/02/05', '1983/04/19', '1969/07/20', '1931/06/13', '1973/03/05', '2004/02/29', '1826/08/28', '2009/05/16/b', '1985/07/21', '1993/09/30', '2001/08/19/c', '1966/07/17/a', '1922/05/06', '1962/12/00', '1970/00/00/f', '1934/04/15', '2005/07/01', '1948/09/02', '1934/04/01/c', '1991/04/24', '2013/06/17', '1923/11/02', '1986/09/00/a', '1934/04/01/b', '1995/09/13', '1961/04/03', '1981/08/24/b', '1988/04/14/b', '2003/05/10', '1952/07/27/d', '1943/05/27', '1896/06/21/R', '2006/02/27', '2014/12/28/d', '2002/06/09/b', '2016/09/18/c', '1890/06/02/R', '2007/04/13/R', '2005/06/07', '1960/09/02', '1996/12/00/a', '1931/09/21/a', '1993/03/22', '1988/04/15/b', '2010/10/28', '1957/00/00/g', '1805/09/00', '1882/01/23/R', '1912/08/30', '1946/07/18/b', '2009/07/30', '1982/07/24/a', '1995/09/03/a', '1839/00/00/a', '2008/04/28/a', '1974/01/09', '1973/12/18', '1968/00/00/c', '1923/10/17', '2011/08/16/a', '2011/07/25', '2003/09/00', '1959/08/14/b', '2009/01/25', '1988/07/17', '2008/09/28/a', '2016/09/05/b', '1995/08/07', '1980/00/00/c', '1932/08/30/a', '2015/05/15', '2006/10/00/b', '2010/07/11', '2010/01/22/b', '1959/04/09//a', '1952/01/23', '1937/01/27', '1973/12/00', '1897/09/06', '1887/12/22/R', '1954/00/00/d', '1959/01/15', '1991/07/01/b', '2002/09/27/a', '1955/07/15', '1993/07/30', '2012/10/18/a', '2002/06/13/R1', '1996/06/06', '1968/02/00', '1963/00/00/b', '1965/04/10', '2005/12/24', '1849/12/01', 'ND/0032', '1990/11/01', '2015/06/14/b', '1617/00/00/R', '1998/07/06/a', '1956/10/20', '1988/09/28', '1945/07/30', '1960/04/30', '2011/02/23', '1950/03/01', '2002/11/28/a', '1942/07/06', '1977/03/13/a', '1914/09/26/R', '1931/00/00/a', '2012/01/02', '1961/06/01', '1951/09/29', '1989/08/06/R', '2014/04/03', '2008/12/30', '1929/02/18', '2009/12/18', '2015/02/08', '2015/01/24/b', '2005/06/22', '1882/12/03', 'ND/0110', '1979/11/27', '2009/02/08', '1959/02/27', '2014/09/13/R', '1835/01/06', '1967/05/13', '1974/09/07', '1962/06/07', '1959/10/07', '2015/09/20/a', '2009/02/12', '1975/02/23', '2009/01/27/R', '1965/01/25', '2006/10/16', '2010/09/04', '1930/06/04', '1946/01/24/a', '1981/00/00/a', '2015/09/05', '1967/09/06', '1985/01/04', 'ND-0106', '2006/05/24', '1950/10/08', '1966/04/08', '2004/02/21', '1968/10/29', '1968/02/26', '1916/12/30', '2012/09/08/a', '1946/12/24/R', '2007/09/16/a', '1942/04/05', '1800/00/00', '1958/12/13', '2007/07/19/b', '1923/05/22', '1990/10/15', '2013/11/22', '0/0336', '1947/04/11', '1853/00/00/d', '2002/10/14', '2008/06/26/R', '1997/01/01', '2000/09/00/b', '2010/02/15', '1959/11/09', '1956/05/00', '2011/09/24/a', '2012/03/22', '1967/12/18', '2015/10/13', '1897/06/09', '1969/05/22', '1934/04/01/a', '1960/08/22', '1903/05/04', '2016/09/06', '1985/03/03', '1998/10/04', '1998/11/02/a', '1975/12/06', '1955/00/00/c', '1911/09/23', '1961/06/18', '1965/12/28', '2007/09/28', '1972/10/14/a', '1888/06/24', '2004/06/14', '1970/00/00/a', '1885/08/17', '1989/12/02', '1863/01/10', '2011/07/07/a', '1985/10/24', '1935/01/24/a', '2008/06/28/b', '1966/08/28', '1978/08/05', '1909/06/18', '1873/07/28', 'ND-0133', '1951/02/19', '1807/01/12', '2003/09/14/a', '1986/10/17', '1921/10/12', '1897/00/00/b', '1964/01/00', '1984/09/30/b', '1958/04/03', '1974/08/10', '1973/06/13', '2016/02/10', '1853/00/00/a', '1826/11/00', '1979/08/26', '1879/11/10', '2012/10/30', '1988/06/16', '1964/12/10/a', '1969/08/00', '1941/06/00', '2014/10/03/a', '2007/08/25', '2001/08/22', '1894/12/11', '2011/11/28', '1953/06/00', '1968/02/20', '1975/04/25', '1953/01/08', '1852/10/23/R', '1900/07/31', '1950/00/00/h', '2016/07/16/b', '1881/00/00/b', '1966/08/27/a', '2007/10/15', '1970/07/05', '1888/02/00', '1893/05/17', '1853/11/08', '2013/11/07/a', '1980/01/25', '1966/05/16/a', '1940/00/00/e', '1955/01/15', '2003/10/05/a', '1966/08/16', '1849/06/08/b', '1908/08/28/R', '1929/03/12', '2005/01/08', '1862/00/00/b', '1922/01/15', '1976/12/18', '1981/02/00', '2009/11/08', '2001/01/06', '1992/01/29/a', '1929/00/00/b', '1889/07/21', '2006/10/31', '1999/11/23', '1992/07/21', '1961/10/09', '2012/11/30', '2013/01/13', '1944/12/18', '1758/00/00', '1845/12/26', '1920/02/03', '1996/05/18', '2006/09/02', '1983/06/00', '1942/11/13/b', '2001/08/27', '2005/12/20', '1958/07/27/a', '1962/01/14/a', '2002/07/04', '1983/00/00/b', 'ND-0148', '1988/08/19', '1945/05/08', '1959/01/27', '2006/03/23', '2013/06/16', '2009/03/17', '1999/07/06', '1993/09/14', '1895/07/16/R', '1877/04/04/', '2009/03/01/b', '1964/01/18', '1960/05/29', '1963/11/28', '1984/08/24', '2015/08/18/b', '1992/03/08/c', '2002/10/11', '2002/02/11', '1999/01/03', '2000/06/10', '1981/09/28', '1962/10/00', '2012/05/06', '1929/06/23', '1932/08/06', '1742/12/17', '1972/06/26/b', '1891/08/30/R', '2007/01/05', '2014/07/13', '2005/08/19', '1884/08/18', '1964/02/11', '2002/05/31/b', '1998/08/13', '1987/00/00/b', '1958/12/27', '2005/06/21', '1960/01/01', '1992/08/00', '1993/06/01', '1952/08/03', '1956/12/09', '1941/00/00/d', '1963/01/28', '2005/06/13', '2006/07/09/a', '1931/08/27', '2013/08/25', '1961/11/14', '2015/01/03', 'ND/0002', '2014/03/12', '2004/10/01', '1993/00/00/b', '1964/08/23', '1985/11/05', '1952/07/05', '2005/04/07', '2014/08/16', '1986/12/04', '1906/09/27/R/a', '1929/12/13', '1987/02/19', '1962/02/05', '1962/09/30', '1996/01/12', '1894/08/01', '1960/04/03/b', '1942/11/01', '1970/00/00/d', '1933/08/28/a', '1964/03/28/b', '1978/11/23', '1955/00/00/e', '2015/09/00', '1899/10/12/b', '2007/07/19/a', '1977/10/30', '2004/07/15', '1944/04/00', '1996/00/00/b', '2014/08/12', '1960/11/06', '1803/03/00', 'ND/0040', '1950/04/09/a', '1989/01/20/a', '2013/08/08/R', '1989/10/01', '1988/10/14', '1961/02/01/b', '1969/05/25', '2009/06/02/b', '1989/01/26/a', '2015/04/29', '1898/10/28', '2005/07/17/a', '1943/11/11', '2006/09/18/R', '1948/07/01', '2000/06/29', '2014/06/01/a', '1956/07/12', '1999/12/26', '2007/08/19/a/', '2006/05/04', '2007/07/17/a', '1891/12/31/R', '1999/05/29', '2013/01/16', '2002/12/01', '2008/07/30', '1880/05/07/R', '1885/04/16/R', '1895/03/15', '1922/10/29', '1872/00/00', '2011/07/13/b', '1937/00/00', '2001/01/24/R', '2000/07/02/b', '1958/07/10', '1964/10/04', '1962/07/03/R', '1995/04/16', '1863/12/14', '1839/00/00/b', '1971/12/16', '1904/09/00', '1956/09/23', '2000/07/16/a', '1961/09/24/a', '1954/04/08', '2011/02/04/R', '1994/03/01', '1965/05/00/a', '1965/08/26', '1968/04/20', '2002/05/22/a', '2010/11/30/a', '1915/01/01', '1959/07/25/b', '2002/08/14', '1953/12/30', '1998/05/29/a', '1998/03/08/a', '1964/01/04', '1972/12/26', '1993/06/10', '1914/02/03', '1905/11/17/R', '1972/09/09', '1994/10/18', '1985/12/22', '2007/05/04', '1889/11/16', '1900/09/15', '1964/08/08', '2008/10/08', '1952/04/00', '2003/04/20/a', '2001/09/08', '1975/02/10', '2012/05/31', '1919/01/15', '1996/11/29/a', '1998/01/17', '2007/09/17', '2004/08/03', '1926/00/00/a', '2011/08/24/b', '2007/12/07', '2007/11/18', '1888/07/13/R', '2015/10/17/b', '1958/07/31/R', '2013/03/10/b', '1828/00/00', '1915/02/06', '2015/05/07', '2005/01/14', '2001/07/06/b', '2008/08/16', '2000/02/03', '1963/12/25', '2007/08/11', 'ND-0136', '1971/08/21', '2013/10/20', '2014/05/10/R', '1983/12/30', '1874/06/15/b/R', '1963/03/30', '2010/01/22/a', '1964/07/00/a', '2002/09/05', '1982/02/13', '2008/04/09/R', '1982/08/29/a', '1996/07/21', '1985/11/11', '1988/10/00', '1969/02/00', '2015/10/09/b', '1999/08/16', '1959/12/29', '1923/00/00/c', '2005/09/04/a', '2014/07/12', '1916/04/25/R', '1953/03/19/R', '2006/01/25', '1993/03/00', '1932/12/09/R', '1958/12/12', '1955/02/04', '1961/10/27', '1938/05/02/R', 'ND/0054', '2015/06/26/c', '1952/05/00', '1968/02/04', '1933/05/03', '2005/08/12', '1918/00/00', '1930/08/16', '2009/11/16/b', '1961/12/28/b', '2013/02/21/a', '2008/03/21', '1939/11/11', '1879/12/24', '1907/07/14/R', '1946/01/24/b', '2010/09/03/a', '2006/12/06', '2001/08/25', '1999/08/23', '2012/08/05', '1890/06/14/R', '2011/05/21/b', '1990/06/23', '2016/09/05/a', '1962/10/25', '1958/09/06', '1966/07/14', '1982/09/30/b', '1927/02/00', '1975/00/00/a', '1905/02/10', '1964/03/28/a', '2015/06/05', '1953/09/18', '1986/08/10', '1984/03/01', '1979/08/05', '2014/07/22', '1864/01/16/R', '1927/12/28', '1976/03/12/b', '1910/05/16/R', '2007/08/15', '1872/04/03/R', '1816/09/03/R', '1985/01/18', '1913/00/00/c', '1949/00/00/c', '1963/02/24', '1836/00/00/a', '1962/01/14/b', '1984/00/00/a', '2003/09/13/a', '2009/12/20/b', '2015/07/26/b', '2011/08/17/c/', '2007/01/19', '1888/08/14', '1991/06/26', '1974/00/00/b', '1965/10/10', '2000/10/06/b', '2015/12/21/a', '2007/01/25/a', '2004/09/08', '2002/04/01', '1961/02/00', '1985/00/00/f', '1936/12/30', '2009/08/29', '1960/02/27/b', '1966/07/17/b', '1924/03/24', '1862/07/25', '2006/05/27', '1853/00/00/b', '2013/09/29/b', '2002/06/11/b', '1968/10/13', '1966/11/14', '1962/05/29', '1912/03/18', '1927/01/08/R', '1922/12/14', '1890/00/00/e', '2012/02/20', '1985/07/00', '2006/08/13', '2009/01/00', '1990/01/12', '1822/04/15', '1920/07/14', '1992/12/28', '1998/11/05', '2003/07/00/b', '1957/04/13', '1967/05/09', '2007/11/00', '1932/10/11', '1963/04/08', '2005/02/04', '1876/00/00/a', '2003/08/12', '1992/01/06', '1943/00/00/d', '1965/10/00', '1965/01/10', '1967/03/20', '1906/09/27/R/b', '1975/10/21', '1856/02/06', '2007/07/04', '1991/02/12', '1974/01/07/c', '1940/00/00/d', '1901/12/01', '2016/03/13', '2010/05/18/a', '1987/11/21', '1950/00/00/i', '2006/06/24', '1898/00/00/b', '1970/01/23/d', '1950/00/00/l', '1887/01/20', '1862/12/19/R', '1968/03/10', '1960/02/03', '1932/08/10', '2015/08/22/a', '2015/09/03', '1923/06/06', '1994/07/08/b', '1949/00/00/b', '1982/09/19', '2001/03/00', '2009/03/19/a', '1934/01/27', '1885/04/09', '1893/06/22', '1974/04/20', '1965/02/04', '2000/12/05', '2007/04/01', '2005/11/21', '1901/06/29/R', '2013/11/30', '1984/11/11', '1971/10/02', '1935/11/13', '1965/06/00/b', '1940/09/00', 'ND/0026', '1920/01/24/R/b', '2012/01/15', '1985/09/28', '1961/12/28/a', '1975/07/23', '2008/07/23', '1979/03/11', '1910/11/28', '1960/08/04/b', '1972/01/01/c', '1915/11/10', '1960/04/00/a', '1931/08/06/R', '1963/09/10', '1921/01/11/R', '1946/06/28', '1959/09/00', '1967/03/19', '1994/09/21', '1988/08/11', '1998/09/00', '1926/07/08', '2012/04/11', '2009/09/15', '1847/00/00/c', '1981/11/09', '1960/07/03', '1981/07/07', '1902/08/24/R', '1991/11/19', '1983/11/10', '2011/08/26', '1957/05/07', '2007/09/13', '2005/07/27', '1975/07/30/b', '1964/01/11', '2013/10/05', '1982/09/25', '1993/11/12', 'ND-0119', '1959/04/27', '1960/02/07', '1916/07/12/c', '2003/04/21/b', '0/0214', '2000/03/00', '1879/03/19', '1929/01/05', '1967/03/09', '1990/08/19/b', '2001/09/07/b', '2012/06/14/d', '1905/07/29', '2013/09/25', '1991/01/09', '1940/03/31', '1924/10/31/R', '2002/04/12', '2004/06/26/b', '1928/06/24/R', '2016/04/18', '1972/08/29', '2008/04/20/b', '2007/07/18/b', '1931/08/30', '1972/02/20', '1942/03/04', '2011/01/31', '1907/00/00/b', '1913/00/00/a', '1913/00/00/d', '2010/09/06/R', '1958/06/26', '1912/02/22', '1972/12/24', '2010/12/01/b', '1929/01/06/R', '1875/11/27/R', '1957/02/24', '1991/06/29', '1894/04/28/a/R', '1879/09/22', '1992/09/10', '1939/10/04', '1956/00/00/c', '2010/08/10/b', '2005/11/25/a', '1941/01/00', '1957/00/00/e', '1999/06/12', '1996/10/28/b', '1881/08/16/R', '2002/12/24', '1919/01/17', '2014/07/20', '1958/00/00/i', '1991/11/14', '1989/09/10', '2012/03/15', '2013/08/05', '2013/04/04', '1932/04/16/a', '1907/09/18/R', '1942/00/00/h', '1980/03/15', '1996/09/18', '1939/00/00/c', '1907/09/11', '1965/04/04/b', '1947/04/06', '1991/09/19', '2008/03/28/a', '1961/01/25', 'ND/0052', '1971/00/00/c', '1994/07/24', '2006/08/22/a', '1905/01/01', '1959/00/00/b', '1887/02/08', '1947/11/08/a', '1969/06/12', '1991/05/26', '2000/00/00', '1996/12/29', '1999/06/09', '1995/11/29', '1987/00/00/a', '1983/00/00/c', '1910/00/00/b', '1978/01/06', '2008/07/26/b', '1997/08/14/a', '1932/08/09', '1872/02/26', '1942/01/18', '1961/02/17/b', '1956/07/28', '1966/01/09', '2006/05/19', '1949/06/13', '1992/05/31', '1990/10/27', '2004/10/09/a', '1960/09/18', '1913/05/02', '2000/02/19', '2010/01/12', '1999/09/16', '1989/08/22/b', '1700/00/00/c', '1995/05/24', '1994/09/26', '2010/01/09/c', '1964/10/25', '1939/00/00/a', '2004/06/10/a', '1949/07/16', '1994/09/05', '2003/11/00', 'ND-0118', '1961/07/29', '1998/11/11', '1978/07/19', '1871/00/00/c', '2011/09/02', '1949/11/20', '2000/10/14', '1955/11/16', '2007/08/22', '1993/11/28', '2013/10/08', '1910/12/23/R', '1963/00/00/a', '1890/00/00/b', '1975/05/20', '1959/08/14/a', '2015/06/24/a', '1955/03/00/a', '1983/08/20/a', '1953/07/11', '1904/00/00/b', 'ND/0069', '1954/07/15', '2004/12/26', '1947/03/12', '1977/04/21', '1932/06/26', '2003/08/08', 'ND/0100', '1984/10/14/a', '2016/05/21/a', '1998/08/27', '1997/09/16', '1963/06/01/b', '2000/06/30', '1965/10/16/a', '1837/00/00/a', '1996/09/01/a', '2014/03/13', '1965/11/21/b', '1880/05/02/a', '1947/11/23', '2010/02/11', '2015/03/10', '1935/05/12', '2012/10/16', '1926/03/17', '2003/07/20', '2010/08/08', '1969/01/27', '1967/08/00/b', '1997/01/25', '1928/02/20', '2016/07/24', '1963/02/04', '2013/04/28', '2009/12/29', '1957/12/20', '1969/05/14', '1987/08/20', '2014/08/06', '2016/06/27', '1905/07/00', '2006/06/30/b', '1967/08/07', '2014/05/14', '2012/07/14', '2000/12/11', '1966/09/10', '2011/05/13/a', '1989/04/12', '1939/05/03', '2010/11/15', '2003/04/09', '1983/09/04', '2011/02/12', '1994/04/15', '2016/04/07/a', '2014/10/14', '1902/01/19/R', '1999/11/15', '2012/04/19/b', '2001/07/00', '1962/07/10', '1963/11/04', '2005/11/24', '1968/10/10', '1937/06/15', '1997/07/02/R', '2014/03/21', '1993/00/00/a', 'ND-0135', '1956/00/00/a', '2016/09/04', '2009/04/03', '2016/04/23', '1984/11/08', '1956/01/16/R', '1945/09/23', '2014/08/28', '2006/03/22', '2013/06/25/b', '1985/10/12', '1956/00/00/e', '1924/11/21', '1885/11/26', '2008/06/24', '2000/06/09/b', '1963/02/08', '1934/08/05', '1965/00/00/d', '1924/04/22', '2005/02/26', '2012/10/07', '1936/07/00', '1928/02/00/a', '1902/08/08', '2014/03/29', '1994/04/16', '1937/09/11', '1938/00/00/a', '2016/07/04', '2000/07/22', '1896/12/20', '1883/09/14/R', '1959/01/25', '1942/03/08', '2006/06/17', '1962/08/23', '1932/05/00', '1979/05/03', '1995/09/17', '1962/09/22', '2000/07/09', '1960/01/07', '1957/02/02', '1983/03/00', '1960/10/00/b', '1935/03/13', '2004/03/16', '1902/06/00', '1986/10/05', '1959/06/14/a', '1864/00/00', '1927/04/08', '2015/05/09', '1920/11/22', '1968/02/18', '1978/12/12', '1956/10/00', '1962/07/07', '2002/06/16', '2015/10/19', '1986/11/04', '1997/01/03/a', '1983/06/22', '2016/04/07/b', '2003/07/15', '1973/00/00/b', '1963/11/25', '1954/08/12/a', '1960/06/24', '1873/06/09/R', '2011/08/17/b/', '1916/04/03', '2004/05/29', '2013/10/11', '1893/10/16', '1880/05/02/b', '2000/05/07/a', '2000/09/12', '1998/12/22', '1992/08/18', '1971/12/23', '1936/02/04', '2007/09/27/b', '1933/05/24', '2013/07/02',

In [76]:
data.head(3)

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,Age,Injury,Fatal (Y/N),Time,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,
0,2016.09.18.c,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,16,Minor injury to thigh,N,13h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.c-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016/09/18/c,2016.09.18.c,5993,NaN,NaN,2016/09/18/c
1,2016.09.18.b,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,Chucky Luciano,M,36,Lacerations to hands,N,11h00,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.b-Luciano.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016/09/18/b,2016.09.18.b,5992,NaN,NaN,2016/09/18/b
2,2016.09.18.a,18-Sep-16,2016,Unprovoked,USA,Florida,"New Smyrna Beach, Volusia County",Surfing,male,M,43,Lacerations to lower leg,N,10h43,NaN,"Orlando Sentinel, 9/19/2016",2016.09.18.a-NSB.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2016/09/18/a,2016.09.18.a,5991,NaN,NaN,2016/09/18/a